### ISSUE TITLE
Lack of informantion

### ISSUE THREAD

**Issue by kcpetersen111** [starwarsnerd77/ImBoredApp#2]
This project gives very little information beyond the fact you are bored. Is this a new thing, What did you do before to not be bored, Is this caused by something? A README and a description would help greatly

**Comment by starwarsnerd77** [comment]
Thank you for your interest in this project! I apologize for the lack of information provided. I will add a README and a description as soon as possible so that you can learn more about this project. Thank you for your patience and understanding. Please reference Issue #1 for updates on the README.
